name: compile-test-lint
description: "Will it work"
inputs:
  before-test-action:
    description: 'Actions to run before test'
runs:
  using: "composite"
  steps:
    - name: "Compile"
      run: echo 'Compile'
      shell: bash
    - run: echo Hello ${{ inputs.before-test-action }}.
      name: "Before test"
      shell: bash
      # uses: ${{ inputs.before-test-action }}
    - run: echo 'Test'
      name: "Test"
      shell: bash
    - run: echo 'Lint'
      name: "Lint"
      shell: bash
