  on:
    push:
      branches:
        - main

  jobs:
    compile:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'compile'
          name: "Compile"
    test:
      runs-on: ubuntu-latest
      needs:
        - compile
      steps:
        - run: echo 'Build'
          name: "Test"
    lint:
      runs-on: ubuntu-latest
      needs:
        - compile
      steps:
        - run: echo 'Build'
          name: "Test"

    deploy-staging:
      runs-on: ubuntu-latest
      environment: staging
      needs:
        - lint
        - test
      steps:
        - run: echo 'Deploy to staging'
          name: "Deploy to staging"

    deploy-production:
      runs-on: ubuntu-latest
      environment: staging
      needs:
        - deploy-staging
      steps:
        - run: echo 'Deploy to production'
          name: "Deploy to production"
