  on:
    push:
      branches:
        - main
  jobs:
    compile:
      runs-on: ubuntu-latest
      steps:
        - run: echo 'compile'
          name: "Compile"
    test:
      runs-on: ubuntu-latest
      needs:
        - compile
      steps:
        - run: echo 'Build'
          name: "Test"
    lint:
      runs-on: ubuntu-latest
      needs:
        - compile
      steps:
        - run: echo 'Build'
          name: "Test"
