on:
  push:
    branches:
      - main
name: Build, Test, Deploy
jobs:
  compmile-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: bright/github-workflows-examples/.github/actions/compile-test-lint@main
        with:
          before-test-action: actions/setup-node@v3
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - lint
      - test
    steps:
      - run: echo 'Deploy to staging'
        name: "Deploy to staging"

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - deploy-staging
    steps:
      - run: echo 'Deploy to production ‼️'
        name: "Deploy to production"
